name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # یا جو بھی ورژن آپ استعمال کر رہے ہوں

      - name: Navigate to project folder
        run: cd your_project_folder_name

      - name: Get dependencies
        run: flutter pub get
        working-directory: ./your_project_folder_name

      - name: Build APK
        run: flutter build apk
        working-directory: ./your_project_folder_name

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: your_project_folder_name/build/app/outputs/flutter-apk/app-release.apk
